"""removed name from user registration

Revision ID: 049517ee378b
Revises: 5e77cdf006ba
Create Date: 2022-09-25 09:54:40.240350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049517ee378b'
down_revision = '5e77cdf006ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
