"""adding basket model

Revision ID: 1bacb614a113
Revises: 1d4a9e634d30
Create Date: 2022-10-09 14:18:50.613964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bacb614a113'
down_revision = '1d4a9e634d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_basket_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basket'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket')
    # ### end Alembic commands ###
