"""made item name unique

Revision ID: 1d4a9e634d30
Revises: d40751a4c915
Create Date: 2022-10-09 10:13:52.075806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4a9e634d30'
down_revision = 'd40751a4c915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ingredients_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ingredients_name'), type_='unique')

    # ### end Alembic commands ###
