"""basket update qty

Revision ID: 423d8c6fde09
Revises: a7d626fdc12c
Create Date: 2022-10-17 21:44:58.599178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423d8c6fde09'
down_revision = 'a7d626fdc12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('quatity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quatity', sa.INTEGER(), nullable=False))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
