"""adding cascade delete

Revision ID: 52366b30aa3d
Revises: 
Create Date: 2022-10-17 19:34:36.853532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52366b30aa3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basket')),
    sa.UniqueConstraint('basket_title', name=op.f('uq_basket_basket_title'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('title', name=op.f('uq_recipes_title'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('basketrecipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['basket.id'], name=op.f('fk_basketrecipes_basket_id_basket')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basketrecipes'))
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_ingredients_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients')),
    sa.UniqueConstraint('name', name=op.f('uq_ingredients_name'))
    )
    op.create_table('recipemethods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipemethods_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipemethods'))
    )
    op.create_table('ingredientrecipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_ingredientrecipe_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_ingredientrecipe_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredientrecipe'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredientrecipe')
    op.drop_table('recipemethods')
    op.drop_table('ingredients')
    op.drop_table('basketrecipes')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_table('categories')
    op.drop_table('basket')
    # ### end Alembic commands ###
