"""basket changes

Revision ID: 548bb9af202e
Revises: 423d8c6fde09
Create Date: 2022-10-18 12:29:53.359608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548bb9af202e'
down_revision = '423d8c6fde09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_basket_title'), ['title'])
        batch_op.drop_constraint('fk_basket_recipe_id_recipes', type_='foreignkey')
        batch_op.drop_column('recipe_id')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('basketrecipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basket_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_basketrecipes_recipe_id_recipes'), 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_basketrecipes_basket_id_basket'), 'basket', ['basket_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basketrecipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_basketrecipes_basket_id_basket'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_basketrecipes_recipe_id_recipes'), type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('recipe_id')
        batch_op.drop_column('basket_id')

    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('recipe_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_basket_recipe_id_recipes', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(batch_op.f('uq_basket_title'), type_='unique')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
