"""second db commit

Revision ID: d40751a4c915
Revises: fd34c9ef3d63
Create Date: 2022-10-05 21:37:19.857066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40751a4c915'
down_revision = 'fd34c9ef3d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredientrecipe', schema=None) as batch_op:
        batch_op.alter_column('ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_ingredientrecipe_ingredient_id_ingredients', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ingredientrecipe_ingredient_id_ingredients'), 'ingredients', ['ingredient_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredientrecipe', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ingredientrecipe_ingredient_id_ingredients'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ingredientrecipe_ingredient_id_ingredients', 'ingredients', ['ingredient_id'], ['id'])
        batch_op.alter_column('ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
