"""adding basket model quantity

Revision ID: d816ca8d6d42
Revises: 1bacb614a113
Create Date: 2022-10-09 14:25:25.452526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd816ca8d6d42'
down_revision = '1bacb614a113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
